INCLUDE_FLAGS	= -I./../../CryEngine/CryCommon -I./../../CryEngine/CryAction
LIBS = 
ADD_OBJECTS =

OUTPUT = game
PROJECT = GameDll
OUTPUT_TYPE = incr_obj
OUTPUT_TYPE_LINUX = dynamic_lib

CXXFLAGS_OPT_LEVEL = -O2

include ../../CryEngine/CryCommon/Makefile.include

